2nd review
2heoh/yap_url_shortener pull request #3
Opened 2022-01-06 11:36 UTC by 2heoh

Упоролся с файлами, вышло как-то не очень красиво, очень интересна обратная связь :)

2022-01-11 18:26 UTC, lugingf requested changes
С файлами всегда вечно жопа)))
Но тут у меня никаких замечаний по этому поводу.
Больше комменты по организации кода. А так все хорошо :)

2022-01-11 18:26 UTC, lugingf commented on cmd/shortener/handlers/request_test.go
> +//type errReader int
Это лишнее?

2022-01-11 18:26 UTC, lugingf commented on cmd/shortener/handlers/request_test.go
> +		//{
И это )

2022-01-11 18:26 UTC, lugingf commented on cmd/shortener/main.go
> +	var repo repositories.Repository = repositories.NewInmemoryURLRepository()
Всю инициализацию репозитория хочется куда-нибудь спрятать под какой-нибудь `repository.Init()`

2022-01-11 18:26 UTC, lugingf commented on cmd/shortener/main.go
> +		repo = repositories.NewFileURLRepository(cfg.FileStoragePath)
Ну и тут не очень красиво. Мы сначала создаем `inmemory`, аллоцируем под него память, еще что-то можем делать, а потом в случае чего - под нож все и реаллоцируем заново :)

2022-01-11 18:26 UTC, lugingf commented on cmd/shortener/main.go
> +	var repo repositories.Repository = repositories.NewInmemoryURLRepository()
Вот кстати прошлый `NewURLRepository()` оставить, только теперь бы в него конфиг передать, чтобы оно под капотом там разобралось какой из вариантов он нам вернет. А возвращать может как раз интерфейс репозитория

2022-01-11 18:26 UTC, lugingf commented on cmd/shortener/repositories/file_storage.go
> +type NotFoundError struct {
А зачем через структуру? Может просто "not found" и все?

2022-01-15 12:23 UTC, 2heoh commented on cmd/shortener/repositories/file_storage.go
> +type NotFoundError struct {
Это я экспериментировал с ошибками как лучше, прикол в том что я в тексте ошибки получать id и хотел посмотреть как и такая проверка мне не очень нравится:
if err != nil && err.Error() == "id is not found: "+id {
хотя избежать её я всё равно не смог, как в go в такой ситуации принято?

2022-01-15 12:26 UTC, 2heoh commented on cmd/shortener/handlers/request_test.go
> +		//{
оставил на чтобы не забыть обсудить - у меня в хэндлере не покрыта тестами ситуация когда чтение body выдаёт ошибку:
```
	b, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)

		return
	}
```
 но как это в тесте сделать я не смог понять, есть какой-то способ дотянуться?

2022-01-18 08:23 UTC, lugingf commented on cmd/shortener/repositories/file_storage.go
> +type NotFoundError struct {
Часто перечень ошибок объявляют прям готовыми переменными
Вот так мы делали, например:
```
var (
	ErrNotEnoughSlots   = errors.New("not enough slots")
	ErrUnknownQueueType = errors.New("unknown queue type")
	ErrQueueNotFound    = errors.New("queue not found")
)
```

2022-01-18 08:24 UTC, lugingf commented on cmd/shortener/handlers/request_test.go
> +		//{
Я бы предложил тестировать не хэндлеры отдельно. А прям со стороны сервера

2022-01-18 08:24 UTC, lugingf approved these changes
Давай двигаться дальше :)

2022-01-18 09:39 UTC, merged